# Generated by Django 4.1.1 on 2022-11-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
